/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capa_presentacion;

import utilidades.Customizable;
import utilidades.ImagenController;

/**
 *
 * @author Alex
 */
public class CrearCuenta extends javax.swing.JFrame {
    Customizable personalizado = new Customizable();


    /**
     * Creates new form IniciarSesion
     */
    public CrearCuenta() {
        initComponents();
        personalizado.cambiarColor(Username);
        personalizado.cambiarColor(password);
        personalizado.cambiarColor(email);
        ImagenController.setImageLabel(image, "src/imagenes/lg.png");
        AplicarStyle();
    }
    
    private void AplicarStyle()
    {
        personalizado.StyleButton(SignIn);
    }
    
    
    

   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backround = new javax.swing.JPanel();
        welcome = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        SignIn = new javax.swing.JButton();
        labelUsername1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        notUse = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backround.setBackground(new java.awt.Color(255, 255, 255));
        backround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setBackground(new java.awt.Color(150, 194, 219));

        Login.setBackground(new java.awt.Color(102, 102, 102));
        Login.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Login.setForeground(new java.awt.Color(51, 51, 51));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Iniciar Sesion");
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Username.setBackground(new java.awt.Color(150, 194, 219));
        Username.setForeground(new java.awt.Color(102, 102, 102));
        Username.setText("Ingrese su usuario");
        Username.setActionCommand("<Not Set>");
        Username.setBorder(null);
        Username.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Username.setInheritsPopupMenu(true);
        Username.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsernameMousePressed(evt);
            }
        });

        password.setBackground(new java.awt.Color(150, 194, 219));
        password.setForeground(new java.awt.Color(102, 102, 102));
        password.setText("********");
        password.setBorder(null);
        password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        password.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        password.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        labelUsername.setForeground(new java.awt.Color(51, 51, 51));
        labelUsername.setText("Email");

        labelPassword.setForeground(new java.awt.Color(51, 51, 51));
        labelPassword.setText("Contraseña");

        SignIn.setBackground(new java.awt.Color(132, 185, 215));
        SignIn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        SignIn.setForeground(new java.awt.Color(51, 51, 51));
        SignIn.setText("Sign In");
        SignIn.setBorderPainted(false);
        SignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignIn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        labelUsername1.setForeground(new java.awt.Color(51, 51, 51));
        labelUsername1.setText("Usuario");

        email.setBackground(new java.awt.Color(150, 194, 219));
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setText("example@gmail.com");
        email.setBorder(null);

        javax.swing.GroupLayout welcomeLayout = new javax.swing.GroupLayout(welcome);
        welcome.setLayout(welcomeLayout);
        welcomeLayout.setHorizontalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsername1)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword)
                    .addComponent(SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsername)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        welcomeLayout.setVerticalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(labelUsername1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(labelUsername)
                .addGap(18, 18, 18)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(labelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        backround.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 420, 580));

        image.setText("imagen");
        backround.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 310, 330));

        notUse.setBackground(new java.awt.Color(229, 237, 241));

        javax.swing.GroupLayout notUseLayout = new javax.swing.GroupLayout(notUse);
        notUse.setLayout(notUseLayout);
        notUseLayout.setHorizontalGroup(
            notUseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        notUseLayout.setVerticalGroup(
            notUseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        backround.add(notUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 150, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameMousePressed

    /**
     * @param args the command line arguments
     */
    
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JButton SignIn;
    private javax.swing.JTextField Username;
    private javax.swing.JPanel backround;
    private javax.swing.JTextField email;
    private javax.swing.JLabel image;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelUsername1;
    private javax.swing.JPanel notUse;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel welcome;
    // End of variables declaration//GEN-END:variables
}
